# Generated by Django 6.0.2 on 2026-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SLABreach",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "breach_type",
                    models.CharField(
                        choices=[
                            ("response", "Response Time Breached"),
                            ("resolution", "Resolution Time Breached"),
                        ],
                        max_length=10,
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("breached_at", models.DateTimeField(auto_now_add=True)),
                ("notified", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "jrd_sla_breaches",
                "ordering": ["-breached_at"],
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "response_time_hours",
                    models.PositiveIntegerField(
                        help_text="Maximum hours for first response"
                    ),
                ),
                (
                    "resolution_time_hours",
                    models.PositiveIntegerField(
                        help_text="Maximum hours for resolution"
                    ),
                ),
                (
                    "escalation_time_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Hours after which to auto-escalate (0 = disabled)",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SLA Policy",
                "verbose_name_plural": "SLA Policies",
                "db_table": "jrd_sla_policies",
                "ordering": ["priority", "name"],
            },
        ),
    ]
