# Generated by Django 6.0.2 on 2026-02-20 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sla", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slabreach",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla_breaches",
                to="tickets.ticket",
            ),
        ),
        migrations.AddIndex(
            model_name="slapolicy",
            index=models.Index(
                fields=["priority", "is_active"], name="idx_sla_prio_active"
            ),
        ),
        migrations.AddField(
            model_name="slabreach",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="breaches",
                to="sla.slapolicy",
            ),
        ),
        migrations.AddIndex(
            model_name="slabreach",
            index=models.Index(
                fields=["ticket", "breach_type"], name="idx_breach_ticket_type"
            ),
        ),
        migrations.AddIndex(
            model_name="slabreach",
            index=models.Index(fields=["breached_at"], name="idx_breach_time"),
        ),
    ]
