# Generated by Django 6.0.2 on 2026-02-20 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(max_length=300, unique=True, verbose_name="Slug"),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Supports HTML/Markdown", verbose_name="Content"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short summary shown in search results",
                        max_length=500,
                        verbose_name="Excerpt",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views"),
                ),
                (
                    "helpful_yes",
                    models.PositiveIntegerField(default=0, verbose_name="Helpful: Yes"),
                ),
                (
                    "helpful_no",
                    models.PositiveIntegerField(default=0, verbose_name="Helpful: No"),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Only visible to staff members",
                        verbose_name="Internal Only",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KB Article",
                "verbose_name_plural": "KB Articles",
                "db_table": "jrd_kb_articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleAttachment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        upload_to="kb_attachments/%Y/%m/", verbose_name="File"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Original Filename"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Size (bytes)"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="knowledge_base.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "KB Attachment",
                "verbose_name_plural": "KB Attachments",
                "db_table": "jrd_kb_attachments",
            },
        ),
        migrations.CreateModel(
            name="KBCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Category Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tailwind/Heroicon class name",
                        max_length=50,
                        verbose_name="Icon CSS Class",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="knowledge_base.kbcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "KB Category",
                "verbose_name_plural": "KB Categories",
                "db_table": "jrd_kb_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="knowledge_base.kbcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="kbcategory",
            index=models.Index(fields=["slug"], name="idx_kbcat_slug"),
        ),
        migrations.AddIndex(
            model_name="kbcategory",
            index=models.Index(fields=["parent", "is_active"], name="idx_kbcat_parent"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="idx_kbart_slug"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "is_internal"], name="idx_kbart_status"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "status"], name="idx_kbart_cat_status"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["-views_count"], name="idx_kbart_views"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["-published_at"], name="idx_kbart_published"),
        ),
    ]
