# Generated by Django 4.2.28 on 2026-02-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short summary shown in search results",
                max_length=500,
                verbose_name="Excerpt",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_description",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Meta Description"
            ),
        ),
    ]
