# Generated by Django 4.2.28 on 2026-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0002_alter_article_excerpt_alter_article_meta_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short summary shown in search results",
                max_length=255,
                verbose_name="Excerpt",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Meta Description"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
