# Generated by Django 4.2.28 on 2026-02-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livechat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chatmessage",
            table="jrd_chat_messages",
        ),
        migrations.AlterModelTable(
            name="chatroom",
            table="jrd_chat_rooms",
        ),
    ]
