# Generated by Django 6.0.2 on 2026-02-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_profile_completed",
            field=models.BooleanField(default=False, verbose_name="Profile Completed"),
        ),
    ]
