# Generated by Django 6.0.2 on 2026-02-20 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Report Name")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ticket_summary", "Ticket Summary"),
                            ("agent_performance", "Agent Performance"),
                            ("sla_compliance", "SLA Compliance"),
                            ("category_breakdown", "Category Breakdown"),
                            ("customer_satisfaction", "Customer Satisfaction"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Saved filter parameters (date range, agent, etc.)",
                        verbose_name="Filters",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Report",
                "verbose_name_plural": "Saved Reports",
                "db_table": "jrd_saved_reports",
                "ordering": ["-updated_at"],
            },
        ),
    ]
