# Generated by Django 6.0.2 on 2026-02-20 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True, default="", verbose_name="Action Taken"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="Error"),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Automation Log",
                "verbose_name_plural": "Automation Logs",
                "db_table": "jrd_automation_logs",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Rule Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("ticket_created", "Ticket Created"),
                            ("ticket_updated", "Ticket Updated"),
                            ("ticket_assigned", "Ticket Assigned"),
                            ("ticket_commented", "Comment Added"),
                            ("sla_breach", "SLA Breach"),
                            ("ticket_idle", "Ticket Idle"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Trigger Event",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON conditions to match against ticket fields.",
                        verbose_name="Conditions",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("assign_agent", "Assign to Agent"),
                            ("change_priority", "Change Priority"),
                            ("change_status", "Change Status"),
                            ("add_tag", "Add Tag"),
                            ("send_notification", "Send Notification"),
                            ("escalate", "Escalate Ticket"),
                            ("add_comment", "Add Internal Note"),
                        ],
                        max_length=30,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "action_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON parameters for the action to execute.",
                        verbose_name="Action Parameters",
                    ),
                ),
                (
                    "priority_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers execute first.",
                        verbose_name="Execution Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "stop_processing",
                    models.BooleanField(
                        default=False,
                        help_text="If True, stop evaluating further rules after this one matches.",
                        verbose_name="Stop Processing",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Automation Rule",
                "verbose_name_plural": "Automation Rules",
                "db_table": "jrd_automation_rules",
                "ordering": ["priority_order", "-created_at"],
            },
        ),
    ]
