# Generated by Django 6.0.2 on 2026-02-20 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automation", "0001_initial"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="automationlog",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_logs",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="automationlog",
            name="rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="automation.automationrule",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["trigger_event", "is_active"], name="idx_rule_trigger_active"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(fields=["priority_order"], name="idx_rule_priority"),
        ),
        migrations.AddIndex(
            model_name="automationlog",
            index=models.Index(
                fields=["rule", "executed_at"], name="idx_autolog_rule_date"
            ),
        ),
        migrations.AddIndex(
            model_name="automationlog",
            index=models.Index(
                fields=["ticket", "executed_at"], name="idx_autolog_ticket_date"
            ),
        ),
    ]
