# Generated by Django 6.0.2 on 2026-02-20 12:07

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sla", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "color",
                    models.CharField(
                        default="#6366f1", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "jrd_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                ("color", models.CharField(default="#8b5cf6", max_length=7)),
            ],
            options={
                "db_table": "jrd_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ticket_id",
                    models.CharField(
                        db_index=True,
                        default=tickets.models.generate_ticket_id,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "description",
                    models.TextField(help_text="Rich text description of the issue"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=15,
                    ),
                ),
                (
                    "sla_response_deadline",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "sla_resolution_deadline",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("sla_response_met", models.BooleanField(blank=True, null=True)),
                ("sla_resolution_met", models.BooleanField(blank=True, null=True)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("email", "Email"),
                            ("api", "API"),
                            ("phone", "Phone"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                ("is_escalated", models.BooleanField(db_index=True, default=False)),
                ("escalation_level", models.PositiveSmallIntegerField(default=0)),
                (
                    "csat_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Customer satisfaction 1-5", null=True
                    ),
                ),
                ("csat_feedback", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="tickets.category",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sla_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="sla.slapolicy",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tickets", to="tickets.tag"
                    ),
                ),
            ],
            options={
                "db_table": "jrd_tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketActivity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status_changed", "Status Changed"),
                            ("priority_changed", "Priority Changed"),
                            ("assigned", "Assigned"),
                            ("reassigned", "Reassigned"),
                            ("commented", "Commented"),
                            ("note_added", "Note Added"),
                            ("escalated", "Escalated"),
                            ("sla_breached", "SLA Breached"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                            ("attachment_added", "Attachment Added"),
                            ("tag_added", "Tag Added"),
                            ("category_changed", "Category Changed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("old_value", models.CharField(blank=True, default="", max_length=255)),
                ("new_value", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "jrd_ticket_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("reply", "Reply"),
                            ("internal_note", "Internal Note"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="reply",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "jrd_ticket_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="attachments/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="Size in bytes"),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticketcomment",
                    ),
                ),
            ],
            options={
                "db_table": "jrd_ticket_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "priority"], name="idx_ticket_status_prio"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["customer", "status"], name="idx_ticket_cust_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_agent", "status"], name="idx_ticket_agent_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["category", "status"], name="idx_ticket_cat_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_at", "status"], name="idx_ticket_created_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["sla_response_deadline"], name="idx_ticket_sla_resp"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["sla_resolution_deadline"], name="idx_ticket_sla_resol"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["is_escalated", "status"], name="idx_ticket_escalated"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketactivity",
            index=models.Index(
                fields=["ticket", "activity_type"], name="idx_activity_ticket_type"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketactivity",
            index=models.Index(
                fields=["ticket", "created_at"], name="idx_activity_ticket_time"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketcomment",
            index=models.Index(
                fields=["ticket", "comment_type"], name="idx_comment_ticket_type"
            ),
        ),
    ]
