# Generated by Django 4.2.28 on 2026-02-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
