# Generated by Django 6.0.2 on 2026-02-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ticket_created", "Ticket Created"),
                    ("ticket_assigned", "Ticket Assigned"),
                    ("ticket_updated", "Ticket Updated"),
                    ("ticket_resolved", "Ticket Resolved"),
                    ("comment_added", "Comment Added"),
                    ("status_change", "Status Changed"),
                    ("priority_change", "Priority Changed"),
                    ("sla_breach", "SLA Breach"),
                    ("automation", "Automation"),
                    ("system", "System"),
                ],
                db_index=True,
                default="system",
                max_length=25,
            ),
        ),
    ]
