# Generated by Django 4.2.28 on 2026-02-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table="jrd_notifications",
        ),
    ]
